name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    env:
      ruby-version: 2.5

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: ./deploy.sh --push-only
